development:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "13478035503"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_2:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "13478035503"
  store: helas-store.myshopify.com
  ignore_files:
  - _sources/*.scss
