development:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "13478035503"
  store: helas-store.myshopify.com
  ignore_files:
  - _sources/*.scss

demo_2:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "15954280495"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_3:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "16998105135"
  store: helas-store.myshopify.com`
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_4:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17452367919"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_5:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17495687215"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_6:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17496342575"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_7:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17546641455"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_8:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17569087535"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_9:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17656578095"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_10:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17658839087"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_11:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17664245807"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_12:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17686757423"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_13:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17713496111"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_14:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17714774063"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_15:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17732239407"
  store: helas-store.myshopify.com
  ignore_files:
  - config/settings_data.json
  - _sources/*.scss

demo_16:
  password: 1a57a5fe7458e5e74ac7a27fb123f395
  theme_id: "17750425647"
  store: helas-store.myshopify.com
  ignore_files:
  - _sources/*.scss
